### PR TITLE
VIR-102: Update table

### PR DESCRIPTION
**Pull request by Peskarhu**
* Update the table to match Figma
* Add new field for kustannuspaikka to the table
* Change layout to be more clear and smooth
* Adjust font sizes, remove borders, colors, backgrounds
* Change the "UUSI VIRKA" button
* Change margins, paddings
* Add new amounts of rows to the bottom header row
* Fix VIR-116 by adding scrollable element to the pop up/view
* Change table headers to match Figma
* Handle clicking table cell header again to not highlight if highlighed
* Fixes placeholder solution for status (active) by checking if active person id

### CODE REVIEW

**Comment by Peskarhu** [comment]
here is the new one:
kuva

**Comment by Peskarhu** [comment]
here is when the user clicks on a cell. User can click again on the same cell to hide the highlight:
kuva

**Comment by Peskarhu** [comment]
and for comparison, here is the older/current: 
kuva

**Comment by nniemi** [comment]
image
There is some translations which have been removed, but I guess these will be changed in the future tickets

**Review by nniemi — DISMISSED** [review]
Looks good and a lot cleaner than before, nice work!

**Review by joonasyr — DISMISSED** [review]
Fixed the import CSV buttons to match this styling after merging develop. Backend pipeline bugged, need @0x464e to manually merge. Other than that looks good and cleaner than before!

**Comment by 0x464e** [comment]
Previous merge overwrite some of Lassi's changes. I believe I brought them back now.

Not sure if something still went badly while merging, or if these two don't yet go together so well, see the image below:

image

The top right buttons are very close to each other, and there is no spacing between the filter accordion and the main table.

**Comment by Peskarhu** [comment]
Updated some things to the layout so the UI looks prettier, such as white arrows and smaller top bar. Also made some easy to add quality of life improvements such as limiting filter input field, and hover color. No more changes on my end to this PR:
 
kuva

**Review by 0x464e — APPROVED** [review]
Good stuff. I quickly fixed one usage of a deprecated prop (https://mui.com/material-ui/migration/migrating-from-deprecated-apis/#props-props-2).

**Pull request merged**
